sequenceDiagram
    %% participant
    actor resAc as Resident_Actor
    participant d as Dorm
    participant res as Resident
    participant room as Room 

    resAc ->> +d:request_cleaning_room(resident_id,room_id)
    d ->> d:search_resident_by_id(resident_id)
    loop
        d ->> +res:get_resident_id()
        res ->> -d:return resident_id

        alt found resident
            res->> d:return resident instance
        else not found resident
            res ->> d:loop find until found resident
        end
    end

    opt not found resident
        d ->> resAc:not found resident
    end

    d ->> d:search_room_by_id(room_id)

    loop
        d ->> +room:get_room_id()
        room ->> -d:return room_id

        alt found room
            room ->> d:return room instance
        else not found room
            room ->>d:loop until found room
        end
    end

    opt not found room
        d ->> resAc:not found room
    end
    