%%{init: {"theme": "forest"}}%%
sequenceDiagram
    %% participant
    actor resAc as Resident_Actor
    participant d as Dorm
    participant res as Resident
    participant b as Building
    participant room as Room

    resAc ->> d:request_cleaning_room(resident_id,room_id)

    d ->> d:search_resident_by_id(resident_id)

    loop for resident in resident_list

        d ->> +res:get_resident_id()
        res ->> d:return resident_id

        alt found resident
            res -->> d:return resident instance
        else not found resident
            res -->> d:loop find until found resident
        end

    end

    opt not found resident
        d -->> resAc:not found resident
    end

    d ->> d:search_building()

    loop for building in building_list
    
        d ->> b:get_building()
        b -->> d:return building instance

        loop for room in building.room_list
        
            alt room.id == room_id
                room -->> d:return room instance and building instance
            else room.id != room_id
                room -->>d:loop until found room

            end
        end
    end

    opt not found room
        d ->> resAc:not found room
    end

    d ->> res:get contract_list from resident instance
    res -->> d:return contract_list

    loop for contract in contract_list

        d ->> +contract:get_room_id()
        contract -->> d:return room_id

        alt contract.room_id == room_id
            contract -->> d:return contract instance
        else contract.room_id != room_id
            contract -->> d:loop until found contract with room_id
        end
    
    end
    
    

    d ->> res:request_cleaning_room(resident_id,room_id)
    create participant cleaning_ticket as Cleaning_Ticket
    res ->> cleaning_ticket:create_cleaning_ticket(resident_id,room_id,report_time,respondsible_cleaner)
    cleaning_ticket -->> res:return ticket 
    res ->> b:add ticket to building
    b -->> res:return request success
    res -->> d:return request success
    d -->> resAc:return request success

    

