---
config:
theme: neo-dark
---
sequenceDiagram
    autonumber
    participant R as Resident
    participant API as FastAPI
    participant D as DormSystem
    participant C as Contract
    participant I as Invoice

    Note over R,API: API Pay Invoice

    R->>+API: POST /pay(invoice_id)
    API->>+D: pay_invoice(invoice_id)

    D->>D: get_invoice_by_id(invoice_id)
    alt invoice not found
        D-->>API: raise LookupError
        API-->>R: HTTP 400
    else invoice found

        D->>+I: validate_for_payment()
        alt status == PAID
            I-->>D: raise ValueError
            D-->>API: raise ValueError
            API-->>R: HTTP 400
        else status == UNPAID
            I-->>-D: pass
        end

        D->>D: find contract where c.invoice_id == invoice_id
        alt contract not found
            D-->>API: raise LookupError
            API-->>R: HTTP 400
        else contract found

            D->>I: invoice.status = PAID
            D->>C: contract.status = ACTIVE

            D-->>-API: contractObj
            API-->>-R: contract_id, contract_status
        end
    end