---
config:
  theme: neo-dark
---
sequenceDiagram
    autonumber
    participant R as Resident
    participant API as FastAPI
    participant D as DormSystem
    participant C as Contract
    

    Note over R,API: API Sign Contract

    R->>+API: POST /sign_contract(contract_id)
    API->>+D: sign_contract(contract_id)

    D->>D: get_contract_by_id(contract_id)
    alt contract not found
        D-->>API: raise LookupError
        API-->>R: HTTP 400
    else contract found

        D->>+C: validate_for_signing()
        alt status != DRAFT
            C-->>D: raise ValueError
            D-->>API: raise ValueError
            API-->>R: HTTP 400
        else status == DRAFT
            C-->>-D: pass
        end

        D->>+C: get_amount()
        C-->>-D: room.price

        D->>D: Invoice(amount, InvoiceType.CONTRACT)

        D->>C: contract.invoice_id = invoice.invoice_id
        D->>C: contract.status = PENDING_SIGN

        D-->>-API: invoiceObj
        API-->>-R: invoice_id, amount, invoice_type
    end