%%{init: {'theme': 'default', 'themeVariables': {'activationBkgColor': '#d9ead3', 'activationBorderColor': '#6aa84f'}}}%%
sequenceDiagram
    actor User as Employee
    participant D as Dorm
    participant E as Employee
    participant R as Resident
    participant I as Invoice

    User ->> D: add_strike(employee_id)

    D ->> D: search_employee_by_id(employee_id)
    loop for employee in employee_list
        D ->> E: getEmployeeID(employee_id)
        E -->> D: return employee_id
        alt found employee
            E -->> D: return employee instance
        else not found employee
            E -->> D: loop find until found employee
        end 
    end

    opt not found employee
        D -->> User: return not found employee
    end

    Note over D:current_date = today's date
    Note over D:residents_to_blacklist_list = []


    loop for resident in resident_list
        Note over D: max_strike = 0

        loop for invoice in resident.invoice_list
            D ->> I: get_invoice_status()
            I -->> D: return status

            opt status == PAID
                D ->> D: continue
            end

            D ->> I: get_date_create()
            I -->> D: return date_create

            D ->> D: calculate_months_old(date_create, current_date)
            Note over D: months_old = (current_date - date_create)//30 find the difference time

            alt months_old >= 3
                D ->> D: strike = 3
            else months_old >= 2
                D ->> D: strike = 2
            else months_old >= 1
                D ->> D: strike = 1
            else
                D ->> D: strike = 0
            end

            opt strike > max_strike
                D ->> D: max_strike = strike
            end
        end

        opt max_strike > 0
            D ->> R: add_strike(max_strike)
            R ->> R: update_strike
            R -->> D: done
        end

        D ->> R: get_strike()
        R -->> D: return strike

        opt resident.strike >= 3
            D ->> D: add_resident_to_residents_to_blacklist_list(resident)
        end
    end

    loop for resident in residents_to_blacklist_list
        D ->> D: remove_from_residents(resident)
        D ->> D: add_to_blacklist(resident)
    end

    D -->> User: return add_strike success