%%{init: {"theme": "forest"}}%%
sequenceDiagram
    autonumber

    actor Resident_Actor
    participant Dorm
    participant Resident
    participant Employee
    participant Room
    participant Technician

    Resident_Actor ->> +Dorm: request_maintenance(resident_id, room_id, issue_category)

    loop resident in dorm.residents
        Dorm ->> +Resident: get_id()
        Resident -->> -Dorm: return id

        alt id == resident_id
            Resident -->> Dorm: return resident
        else id != resident_id
            Resident -->> Dorm: continue
        end
    end

    opt resident not found
        Dorm -->> Resident_Actor: return "resident not found"
    end

    loop room in dorm.rooms
        Dorm ->> +Room: get_id()
        Room -->> -Dorm: return id

        alt id == room_id
            Room -->> Dorm: return room
        else id != room_id
            Room -->> Dorm: continue
        end
    end

    opt room not found
        Dorm -->> Resident_Actor: return "room not found"
    end

    loop employee in dorm.employees
        Dorm ->> +Employee: get_status()
        Employee -->> -Dorm: return status

        alt status == "ACTIVE"
            Employee -->> Dorm: return employee
        else status != "ACTIVE"
            Employee -->> Dorm: continue
        end
    end

    opt no available staff
        Dorm -->> Resident_Actor: return "no available staff"
    end

    Dorm ->> +Employee: start_maintenance(resident, technicians, room, issue_category)

    loop tc in technicians
        Employee ->> +Technician: get_status()
        Technician -->> -Employee: return status

        alt status == "ACTIVE"
            Technician -->> Employee: return tc
        else status != "ACTIVE"
            Technician -->> Employee: continue
        end
    end

    opt no available technician
        Employee -->> Dorm: return "no available technician"
        Dorm -->> Resident_Actor: return "no available technician"
    end

    create participant Maintenance_Ticket
    Employee ->> Maintenance_Ticket: create_maintenance_ticket(reporter, room_id, issue_category, technician_id)
    activate Maintenance_Ticket
    Maintenance_Ticket -->> Employee: return ticket
    deactivate Maintenance_Ticket

    Employee ->> +Technician: assign_ticket(ticket)
    Technician ->> Maintenance_Ticket: update_maintenance_status("FINISH")
    activate Maintenance_Ticket
    Maintenance_Ticket -->> Technician: return
    deactivate Maintenance_Ticket
    Technician -->> -Employee: return "done"

    Employee ->> Maintenance_Ticket: approve_maintenance(self, "APPROVED")
    activate Maintenance_Ticket
    Maintenance_Ticket -->> Employee: return
    deactivate Maintenance_Ticket

    Employee ->> Room: add_maintenance_ticket(ticket)
    Room -->> Employee: return ok

    Employee -->> -Dorm: return result
    Dorm -->> Resident_Actor: return result
    deactivate Dorm
