sequenceDiagram
    actor resAc as Resident_Actor
    participant d as Dorm
    participant res as Resident
    participant b as Booking
    participant c as Contract
    participant r as Room

    resAc ->> +d: change_lease_contract(residentId, currentLeaseContractId, targetRoomId, moveDate)
    d ->> d: search_resident_by_id(residentId)
    activate d
    loop resident in Dorm.residents
        d ->> +res: get_resident_id()
        res -->> -d: return resident_id 

        alt id == residentId
            res -->> d: return resident
        else id != residentId
            res -->> d: continue loop
        end
    end
    deactivate d
    %% something else ->> smth ...
    d -->> -resAc: ggggggg